### PR TITLE
feat: playwright axe dotnet migration

### PR DESCRIPTION
**Pull request by IsaacWalker**
This PR is part of an ongoing collaboration between myself, @TroyWalshProf, Microsoft, and Deque to migrate SeleniumAxeDotnet and PlaywrightAxeDotnet to be an official, Deque-supported Axe integration library.

This PR merges the main branch of [PlaywrightAxeDotnet](https://github.com/IsaacWalker/PlaywrightAxeDotnet) into this repos `/packages/playwright`. This work is licensed under the [MIT License](https://github.com/IsaacWalker/PlaywrightAxeDotnet/blob/main/License.txt).

A large volume of the files is a result of using the Zero-Installs approach of Yarn V2. If desired it is acceptable for me to revert to the traditional approach as part of this PR.

### CODE REVIEW

**Comment by straker** [comment]
@IsaacWalker Is the Playwright.Axe `NodeDependencies` and `.yarn/cache` suppose to be in the pr?

**Comment by IsaacWalker** [comment]
> @IsaacWalker Is the Playwright.Axe `NodeDependencies` and `.yarn/cache` suppose to be in the pr?

Originally that was meant to reduce install time by having an online cache (Yarn V2 zero-installs). I've migrated to yarn v1 for now.

**Review by AdnoC — APPROVED** [review]

**Comment by michael-siek** [comment]
Hey @IsaacWalker do you mind signing the CLA [Contributor License Agreement](https://cla-assistant.io/dequelabs/axe-core-nuget?pullRequest=26)

**Comment by michael-siek** [comment]
- [x] reviewed for security

**Pull request merged**
