### PR TITLE
docs: Reference to Selenium Nuget packages in Playwright README

### PR DESCRIPTION
**Pull request by IsaacWalker**
## Details

The Playwright package README was incorrectly referencing the Selenium NuGet package.

Closes Issue:

### CODE REVIEW

**Review by AdnoC — APPROVED** [review]

**Comment by AdnoC** [comment]
Reviewed for security

**Comment by AdnoC** [comment]
Looks good. However the email associated with the commit is causing our CLA bot to not find you. Could you amend your commit with a different email or associate the email address used with your github account?

**Comment by dbjorge** [comment]
@IsaacWalker, since we haven't heard back from you on amending the commit, I've gone ahead and satisfied the CLA bot by force-pushing an update to the listed commit author to match the one you've used previously in this repo. 3165d29 is the result of running `git commit --amend --author="IsaacWalker <36536997+IsaacWalker@users.noreply.github.com>"` on your original commit.

Thanks for contributing the README fix, apologies for the delay!

**Review by straker — APPROVED** [review]

**Comment by straker** [comment]
Approved for security

**Pull request merged**
